version: '3.4'
services:
    bombdefuse:
        build: .
        image: bomb_defuse:1.0
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html
            - ./src:/var/www/src